Aplicacion/RiegoYCultivo/RiegoYCultivo/urls.py
from django.conf.urls import patterns, include, url, handler404, handler500
from agricultura.views import *

from django.contrib import admin
admin.autodiscover()
# from django.views.generic import RedirectView
from django.conf import settings
from agricultura.views import error404
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'RiegoYCultivo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', base, name="url_inicio"),
    url(r'^agricultura/', include('agricultura.urls', namespace="agricultura")),
    #url(r'^skin-config$', conf_tema , name="url_conf-tema"),
    url(r'^iniciosesion/$', inicioSesion),
    url(r'^cerrarsesion/$', cierre_node),
    url(r'^recuperar_cuenta/(?P<username_user>\w+)/(?P<email_user>.*)/$', verifica_recuperacion_cuenta, name="URLverifica_recuperacion_cuenta"),
    url(r'^recuperar_password/$', cambiar_password, name="URLcambiar_password"),
    url(r'^modular/', include('app_modular.urls')),
    url(r'^empresa/', include('app_empresa.urls', namespace='URLempresa')),
    url(r'^seguridad/', include('app_seguridad.urls')),
    url(r'^iot/', include('iot.urls', namespace='iot')),
    url(r'^reglas/', include('app_eventos.urls', namespace="reglas")),
    url(r'^reportes/', include('app_reportes.urls', namespace='reportes')),
)
if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
    )

handler404=error404
handler500=error500

Aplicacion/RiegoYCultivo/agricultura/urls.py
__author__ = 'Dyuyay'

from django.conf.urls import patterns, url

from archivos.views import *
from especie.views import *
from configuracion.views import *
from parcelas.views import *
from plagas.views import *
from cultivo.views import *
from reportes.views import *
from monitoreo.views import *
from django.views.generic import RedirectView
from django.conf import settings
from views import *

# SECCION TIPO DE SUELO
from configuracion.views_suelo import *

urlpatterns = patterns('',
    url(r'^inicio/$', inicio, name="url_inicio"),
    #url-especies
    url(r'^especie/$', especie, name="url_especie"),
    url(r'^categoria_especie/$', categoria_especie, name="url_categoria_especie"),
    #url-especies-operaciones
    url(r'^categoria_especie_agregar/$', agregar_categoria, name="url_categoria_agregar"),
    url(r'^bajaCategoria/$', baja_categoria),
    url(r'^ver_datos_categoria/$', ver_datos_categoria),
    url(r'^modificar_datos_categoria/$', modificar_datos_categoria),
    url(r'^especie_agregar/$', agregar_especie, name="url_especie_agregar"),
    url(r'^especie_valores/$', valores_especie, name="url_especie_valores"),
    url(r'^bajaEspecie/$', baja_especie),
    url(r'^ver_datos_especie/$', ver_datos_especie),
    url(r'^modificar_datos_especie/$', modificar_datos_especie),
    url(r'^tipos_parametros_especie/$', tipos_parametros_especie),
    # url(r'^verTipos/$', verTipos),

    # url(r'^verParametros/$', verParametros),
    url(r'^parametros_agregar/$', agregar_parametros, name="url_parametros_agregar"),
    url(r'^bajaParametros/$', baja_parametros),
    url(r'^verParametros/(\d+)/$', ver_datos_parametros),
    # url(r'^ingresarNuevoTipoParametro/$', ingresar_datos_tipoParametros),

    url(r'^riego_guardar/$', guardar_riego, name="url_riego_guardar"),
    url(r'^riego_archivo/$', guardar_archivo_formulas, name="url_riego_archivo"),
    url(r'^riego_formulas/$', tipo_riego_formulas, name="url_riego_formulas"),
    url(r'^formula_agregar/$', agregar_formula, name="url_formula_agregar"),
    url(r'^eliminar_formula/$', eliminar_formula),
    url(r'^bajaFormula/$', baja_formula),
    url(r'^tiporiegoformula/$', verTipoRiegoFormula),
    url(r'^ver_datos_riego/$',ver_datos_riego),
    url(r'^modificar_datos_riego/$',modificar_datos_riego),
    url(r'^descargarExcel/(\w+)/$', descargarExcel),


    url(r'^parametros_cultivo/$', parametros_cultivo, name="url_parametros_cultivo"),
    url(r'^copiar_cultivo/$', copiar_cultivo, name="url_copiar_cultivo"),
    url(r'^crear_modelo/$', crear_modelo, name="url_crear_modelo"),

    # TIPOS DE PARAMETROS
    url(r'^parametros_tipo/$', tipos_parametros, name="url_parametros_tipo"),
    url(r'^obtenerTipo/(\d+)/$', ver_datos_tipo),
    url(r'^editarTipo/(\d+)/$', editar_tipo),
    url(r'^bajaTipo/$', baja_tipo),
    url(r'^tipo_agregar/$', tipo_agregar, name="url_tipo_agregar"),

    url(r'^tipo_riego/$', tipo_riego, name="url_tipo_riego"),
    url(r'^cultivo_agregar/$', cultivo_agregar, name="url_cultivo_agregar"),
    url(r'^cultivo_ver/$', cultivo_ver, name="url_cultivo_ver"),
    url(r'^cultivo_modelos/$', cultivo_modelos, name="url_cultivo_modelos"),
    url(r'^restaurar/$', default_config, name="url_restaurar"),

    url(r'^tiposSuelo/$', tipoSuelo, name="url_tipo_suelo"),
    url(r'^eliminar_suelo/$', eliminar_suelo),
    url(r'^tipo_suelo_agregar/$', agregar_tipo_suelo, name="url_tipo_suelo_agregar"),
    url(r'^bajaSuelo/$', baja_suelo),
    url(r'^verSuelos/(\d+)/$', ver_datos_suelo),
    url(r'^suelo_valores/$', valores_suelo, name="url_suelo_valores"),
    url(r'^tipos_parametros_suelo/$', tipos_parametros_suelo),



    url(r'^detalle_especie/$', obtenerEspecie),
    url(r'^detalle_parcela/$', obtenerParcela),
    url(r'^detalle_riego/$', obtenerRiego),
    url(r'^evotranspiracionInicial/$', confEt0, name="url_et0"),
    url(r'^datosParcela/$', detalleParcela),    #para metodo de hargravens
    url(r'^datosParcela_P/$', detalleParcela_P), #para metodo de Penmant
    url(r'^guardarDatoEvo/$', guardarDatoEvo),  #guardado para metodo de Hargravens
    url(r'^guardarDatoEvoPenman/$', guardarDatoEvoPenman),  #guardado para metodo de Penman Monteith
    url(r'^evotranspiracionInicialP/$', confEt0Penman, name="url_et0P"),

#   parcelas
    url(r'^parcelas/$', parcelas, name="url_parcelas"),
    url(r'^guardarParcela/$', guardarParcela, name="url_guardar_parcela"),
    url(r'^ver_datos_parcela/$', ver_datos_parcela, name="url_datos_parcela"),
    url(r'^modificar_datos_parcela/$', modificar_datos_parcela, name="url_modificar_datos_parcela"),
    url(r'^bajaParcela/$', dar_dbaja_parcela, name="url_dbaja_parcela"),

# zona sensor actuador
    url(r'^zona_riego/(?P<id>.*)/$', zona_riego),
    url(r'^guardarZona/$', guardarZona, name="url_zona_agregar"),
    url(r'^ver_datos_zona/$', ver_datos_zona, name="url_datos_zona"),
    url(r'^modificar_datos_zonas/$', modificar_datos_zonas, name="url_modificar_datos_zonas"),
    url(r'^bajaZona/$', dar_dbaja_zona, name="url_dbaja_zona"),
    url(r'^consulta_sen_act/$', consulta_sen_act),
    url(r'^actualizar_sen_act_zona/$', act_sen_act_zona),

#   archivos de parcelas
    url(r'^parcela/archivos/(?P<parcela_id>.*)/$', archivos, name="url_archivos_por_parcela"),
    url(r'^guardarArchivo/$',guardarArchivo, name="url_guardar_archivo"),
    url(r'^ver_datos_archivo/$', ver_datos_archivo, name="url_datos_archivo"),
    url(r'^modificar_datos_archivo/$', modificar_datos_archivo, name="url_modificar_datos_archivo"),
    url(r'^bajaArchivo/$', dar_dbaja_archivo, name="url_dbaja_archivo"),

#   plagas
    url(r'^guardar_plaga/$', guardar_plaga, name="url_cultivo_plaga"),
    url(r'^bajaPlaga/$', dar_dbaja_plaga, name="url_dbaja_plaga"),

#   cultivos
    url(r'^anadirCultivo/$', anadir_cultivo, name="url_cultivo_anadir"),
    url(r'^anadirCultivo_java/$', anadir_cultivo_java, name="url_cultivo_anadir_java"),
    # url(r'^detalleCultivo/$', detalle_cultivo, name="url_cultivo_detalle"),
    url(r'^detalle/(?P<id>.*)/$', detallado, name="url_cultivo_detalle"),
    url(r'^detalleModelo/(?P<id>.*)/$', detalleModelo, name="url_cultivo_detalle_modelo"),
    url(r'^cosechar/$', cosechar, name="url_cultivo_cosechar"),
    url(r'^agregar_nota/$', agregar_nota, name="url_cultivo_nota"),
    url(r'^eliminar_nota/$', eliminar_nota, name="url_cultivo_nota_e"),
    url(r'^tiene_parcela/$', tiene_parcela, name="url_cultivo_tiene_parcela"),
    url(r'^obtener_datos_suelo/$', obtener_datosSuelo, name="url_cultivo_datosSuelo"),
    url(r'^cambiar_imagen_cultivo/$', cambiarImange, name="url_cambiar_imagen_cultivo"),
    url(r'^editar_imagen_cultivo/$', cambiarImagenes, name="editar_imagen_cultivo"),
    url(r'^agregar_imagen_cultivo/$', agregarImagen, name="editar_imagen_cultivo"),

# Monitoreo y Control
    url(r'^monitoreo/(?P<id>.*)/$',panel_monitoreo, name="url_monitoreo_y_control"),
    url(r'^guardar/$',guardarPanel, name="url_prueba"),
    url(r'^recetearDispositivos$',recetearDispositivos),
    url(r'^consultar_zonas$',cargarZonas),
    url(r'^ultimasLecturas$',ult_lecturas),
    url(r'^envio_accion_actuador$',envio_accion_actuador),
    url(r'^borrado_dispositivos_programado$',borrado_dispositivos_programado),

# reportes a ver si sale :v
    #url(r'^reporte/$', ver_reporte, name="url_reporte"),#reportes
    url(r'^reportes_cultivo/$', reportes_cultivo, name="url_reportes_cultivo"),
    url(r'^formulario/(\d+)/$', frmReporteCultivo),
    url(r'^reporteC/datos/(\d+)/$', datos_Cultivo),

#cosechas
    url(r'^listar_cosechas/$',lista_cosecha),
    url(r'^guardar_cosecha/$',guarda_cosecha),
    url(r'^editar_cosecha/$',edita_cosecha),
    url(r'^consulta_cosecha/$',consulta_cosecha),
    url(r'^arbol/$', templateArbol),
)#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicacion/RiegoYCultivo/iot/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from iot.views import *
from django.contrib import admin
from django.conf import settings
from agricultura.parcelas.views import zona_riego
from iot import views_public
urlpatterns = patterns('',
    # Sensores
    url(r'^inicio/$', base_iot, name="url_sensor"),
    url(r'^sensor/$', openSensor, name="url_sensor"),
    url(r'^sensor/sav/$', guardarSensor,  name="url_sensor_agregar"),
    url(r'^obtenerSensor/(\d+)/$', getSensor),
    url(r'^sensor/mod/$', modificarSensor),
    url(r'^bajaSensor/$', baja_sensor),
    url(r'^eliminar_sen_act/$', eliminar_sen_act),

    url(r'^dispositivo/$', cargarDispositivo, name="url_dispositivo"),
    url(r'^bajaDisp/$', baja_dispositivo),
    url(r'^disp_agregar/$', agregar_dispositivo, name="url_disp_agregar"),
    url(r'^ver_datos_dispositivo/$', ver_datos_dispositivo),
    url(r'^modificar_datos_dispositivos/$', modificar_datos_dispositivos),
    url(r'^getDispositivo/$', getDispositivo),

    url(r'^zona_riego/(?P<id>.*)/$', zona_riego),
    url(r'^visualizar_zonas/$', ver_zonas),
    url(r'^buscar_zonas/$', buscar_zonas),
    url(r'^eliminar_dispositivo/$', eliminar_dispositivo),
    url(r'^verificar_update/$', mostrar_update),

    url(r'^monitoreo_acciones/(\d+)/$', monitoreo_acciones),

    # Permite vicualizar las configuraciones asociadas a un TED
    url(r'^teds/(\d{1,2})$', template_details, name='index'),

    url(r'^dispositivo_info/(?P<dispositivo_mac>.+)/$', views_public.informacion, name='dispositivo_info'),
)

Aplicacion/RiegoYCultivo/agricultura/archivos/views.py
__author__ = 'Dyuyay'
import json

from django.shortcuts import render, render_to_response, RequestContext, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from urlparse import urlparse

from ..models import *
from agricultura.metodos import *

@login_required(login_url="/")
def archivos(request, parcela_id):
    if request.user.is_authenticated():
        dic = armaMenu(request.user.get_all_permissions())
        dic['usuario'] = request.user
        dic['persona'] = obtenerPersona(request)
        dic['roles'] = obtenerRoles(request)
        dic['empresa'] = getEmpresa(request)
        dic['tipo_archivos'] = agr_tipo_archivo.objects.all()
        areas = proy_area.objects.filter(emp_id_id=dic['empresa'])
        subareas = proy_subarea.objects.filter(ar_id=areas)
        dic['parcelas'] = agr_parcela.objects.filter(par_id=subareas)
        if(parcela_id == "all"):
            if request.user.has_perm('agricultura.add_agr_archivo') or request.user.has_perm(
                    'agricultura.list_agr_archivo'):
                dic['archivos'] = agr_archivo.objects.all()
                dic['esGeneral'] = True
                return render(request, "agricultura/archivos/templateArchivos.html", dic)
            else:
                return render_to_response("seguridad/errores/error_403.html", dic,
                                          context_instance=RequestContext(request))
        else:
            if request.user.has_perm('agricultura.add_agr_archivo') or request.user.has_perm(
                    'agricultura.list_agr_archivo'):
                dic['parcela'] = get_object_or_404(agr_parcela, pk=parcela_id)
                dic['archivos'] = agr_archivo.objects.filter(par_id = parcela_id)
                return render(request, 'agricultura/archivos/templateArchivos.html', dic)
            else:
                return render_to_response("seguridad/errores/error_403.html", dic,
                                          context_instance=RequestContext(request))
    else:
        return redirect('/')

@login_required(login_url="/")
def guardarArchivo(request):
    if request.user.is_authenticated():
        if request.method == "POST":
            tipo_archivo = agr_tipo_archivo.objects.get(pk=request.POST.get("select_archivo",""))
            archivo = agr_archivo()
            archivo.arc_estado = request.POST.get("estArchivo","")
            archivo.arc_nombre = request.POST.get("nomArchivo","")
            archivo.arc_uri = request.FILES.get("fileArchivo","")
            parcela = agr_parcela.objects.get(pk=request.POST.get("select_parcela", ""))
            archivo.par_id = parcela
            archivo.tarc_id = tipo_archivo
            archivo.save()
            messages.add_message(request, messages.SUCCESS, "Archivo Guardado")
            return redirect(reverse("agricultura:url_archivos_por_parcela", args=(archivo.par_id.pk,)))
    else:
        return redirect("/")

@login_required(login_url="/")
def ver_datos_archivo(request):
    id = request.GET.get("id","")
    data = {}
    try:
        archivo = agr_archivo.objects.get(pk=id)
        data = {
            'pk':archivo.pk,
            'uri':archivo.arc_uri.url,
            'nombre':archivo.arc_nombre,
            'tipo':archivo.tarc_id.pk,
            'estado':archivo.arc_estado
        }
        return JsonResponse(data, safe=False)
    except Exception as err:
        print err
        data = []
    return JsonResponse(data, safe=False)

@login_required(login_url="/")
def modificar_datos_archivo(request):
    try:
        dic = []
        archivoeditar = agr_archivo.objects.get(pk=request.POST.get("id",""))
        archivoeditar.arc_nombre = request.POST.get("nomArchivo","")
        archivoeditar.tarc_id = agr_tipo_archivo.objects.get(pk=request.POST.get("select_archivo", ""))
        archivoeditar.arc_uri = request.FILES.get("fileArchivo", "")
        archivoeditar.save()
        dic = {'result': 'OK'}
        messages.add_message(request, messages.SUCCESS, 'Registro Actualizado')
    except Exception as error:
        print(error)
        dic = {'result': 'Error al modificar'}
    # data = json.dumps(dic)
    return JsonResponse(dic)

@login_required(login_url="/")
def dar_dbaja_archivo(request):
    id = request.GET.get('id',"")
    estado = request.GET.get('estado', "")
    try:
        bajaArchivo = agr_archivo.objects.get(pk=id)
        if (estado == 'true'):
            bajaArchivo.arc_estado = True
        else:
            bajaArchivo.arc_estado = False
        bajaArchivo.save()
        dic = {'result': 'OK'}
    except Exception as e:
        print(e)
        dic = {
            'result': 'Error al dar de baja el archivo'
        }
    data = json.dumps(dic)
    return HttpResponse(data, content_type="application/json")

Aplicacion/RiegoYCultivo/templates/agricultura/reportes/prueba.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>prueba</title>
</head>
<body>
	<h1>Hola</h1>
</body>
</html>

Aplicacion/RiegoYCultivo/templates/agricultura/reportes/templateCultivoR.html
{% extends "app_reportes/base_r.html" %}

{% block css %}

<link href="/static/agricultura/css/plugins/chosen/chosen.css" rel="stylesheet">
<link href="/static/agricultura/css/plugins/select2/select2.min.css" rel="stylesheet">
<link href="/static/agricultura/css/plugins/cropper/cropper.min.css" rel="stylesheet">
<link href="/static/agricultura/css/plugins/switchery/switchery.css" rel="stylesheet">
<!-- Data Tables -->
<link href="/static/agricultura/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="/static/agricultura/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="/static/agricultura/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<link href="/static/agricultura/css/plugins/footable/footable.core.css" rel="stylesheet">

{% endblock css %}

{% block contenido %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>Reportes</h2>
        <h2 class="pull-right" style="margin-top: -35px;">{{empresa}}</h2>
        <ol class="breadcrumb">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Inicio<span class="caret"></span></a> {% include "dropdown-menu.html" %}
            </li>
            <li>
                <a href="/reportes/inicio/">Módulo Reportes</a>
            </li>
            <li class="active">
                <strong>Reportes de Cultivos</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
        {% if 'agricultura.list_agr_cultivo' in usuario.get_all_permissions %}
		    <div class="col-md-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title hvr-overline-from-left" style="width: 100%;">
                    <h5>Cultivos Ingresados</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                            <input type="text" class="form-control input-sm m-b-xs" id="filter"
                                   placeholder="Search in table">
                            <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="8" data-filter=#filter>
                                <thead>
                                <tr>
                                    <th data-toggle="true">Nombre</th>
                                    <th>Especie</th>
                                    <th>Parcela</th>
                                    <th>Estado</th>
                                    {% if 'agricultura.print_agr_cultivo' in usuario.get_all_permissions %}
                                        <th>Generar</th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tbody>
                                {% for datos in datosCultivo %}
                                <tr>
                                    <td>{{ datos.cult_detalle }}</td>
                                    <td>{{ datos.esp_id.esp_nombre }}</td>
                                    <td>{{ datos.parcela.par_id.sar_nombre }}</td>
                                    <td>
                                        {% if datos.cult_estado %}
                                            <span class="label label-info ">Activo</span>
                                        {% else %}
                                            <span class="label label-danger ">Inactivo</span>
                                        {% endif %}
                                    </td>
                                    {% if 'agricultura.print_agr_cultivo' in usuario.get_all_permissions %}
                                    <td>
                                        <a href="/agricultura/formulario/{{ datos.cult_id}}" >
                                            <i class="fa fa-file-pdf-o"></i></a>
                                    </td>
                                    {% endif %}
                                </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <ul class="pagination pull-right"></ul>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
            </div>
		</div>
    {% endif %}


	</div>

</div>


    <!-- modales -->
    <div class="modal inmodal fade" id="modalVer" tabindex="-1" role="dialog"  aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="animated bounceInRight">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
            <center>
                <img id="imagen" width="400" class="img-circle" height="400">
            </center>
        </div>
    </div>
</div>
    <div class="modal inmodal fade" id="modalParametros" tabindex="-1" role="dialog"  aria-hidden="true" style="display: none;">
        <div class="modal-dialog"> <!-- modal-sm -->
            <div class="modal-content animated bounceInRight">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                        <h4><label class="modal-title" id="nombre">Nombre de especie</label></h4>
                        <cite title="" data-original-title="">Si existen datos seran modificados</cite>
                </div>
                  <div class="modal-body">
                    <form class="form-horizontal" id="form_parametros" name="form_parametros" method="post" enctype="multipart/form-data" action="{% url 'agricultura:url_especie_valores' %}">{% csrf_token %}
                        <div class="row" id="form-Modal">
                        </div>
                        <input type="text" id="id" name="id" class="hide"/>
                    
                </div>
                <div class="modal-body">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                </div>
                </form>
            </div>
        </div>
    </div>

{% endblock contenido %}

{% block scripts %}
<script>
    document.onload = cargarFunciones();
    function cargarFunciones(){
        $('#reportes_cultivos').addClass('active');
    };          
</script>
<script src="/static/agricultura/js/plugins/chosen/chosen.jquery.js"></script>
<script src="/static/agricultura/js/plugins/select2/select2.full.min.js"></script>
<script src="/static/agricultura/js/plugins/cropper/cropper.min.js"></script>
<script src="/static/agricultura/js/plugins/switchery/switchery.js"></script>

<!-- DataTables -->
<script src="/static/agricultura/js/plugins/footable/footable.all.min.js"></script>


<script src="/static/agricultura/scripts/op_especie.js"></script>

{% endblock scripts %}

Aplicacion/RiegoYCultivo/templates/agricultura/reportes/templateLista.html
{% extends "agricultura/base_agricultura.html" %}

{% block contenido %}

    </br>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-list-alt"></i> <label>Lista de Proyectos</label></h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <table class="table table-condensed" id="presentacion">
                                <thead>
                                <tr>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>Fecha de Inicio</th>
                                <th>Fecha de Finalizacion</th>
                                <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in proyectos %}
                                    <tr>
                                        <td>{{ i.proy_nombre }}</td>
                                        <td>{{ i.proy_descripcion }}</td>
                                        <td>{{ i.proy_fecha_ini }}</td>
                                        <td>{{ i.proy_fecha_fin }}</td>
                                        <td><a href="/reportes/proyecto/formulario/{{ i.id }}" class="btn btn-primary">
                                            <i class="fa fa-plus"></i> Ver Más</a>
                                        </td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.onload=inicioTabla()
        function inicioTabla(){
            $('#presentacion').dataTable( {
                  "ordering": false
            } );
        $('#contenedorReportes').addClass('active');
        $('#reporteRiego').addClass('active');
        }

    </script>
{% endblock %}

Aplicacion/RiegoYCultivo/templates/agricultura/reportes/templateReportes.html
{% extends "app_reportes/base_r.html" %}
{% block contenido %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>Reportes</h2>
        <h2 class="pull-right" style="margin-top: -35px;">{{empresa}}</h2>
        <ol class="breadcrumb">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Inicio<span class="caret"></span></a> {% include "dropdown-menu.html" %}
            </li>
            <li>
                <a href="/reportes/inicio/">Módulo Reportes</a>
            </li>
            <li class="active">
                <strong>{{ tituloReporte }}</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>
  <!--   <legend>{{ tituloReporte }}</legend> -->
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <embed src="{{ urlReporte }}" width="100%" height="550" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html">
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script>
    document.onload = cargarFunciones();
    function cargarFunciones(){
        $('#reportes_cultivos').addClass('active');
    };          
</script>
{% endblock scripts %}